spring:
  liquibase:
    enabled: false
  datasource:
    driverClassName: org.firebirdsql.jdbc.FBDriver
    #url: jdbc:firebirdsql:127.0.0.1/3050:c:/fix/6113.fdb?sql_dialect=3&charSet=utf-8&encoding=NONE
    url: jdbc:firebirdsql:127.0.0.1/3050:c:/fix/ronalds/ronalds.fdb?sql_dialect=3&charSet=utf-8&encoding=NONE
    username: SYSDBA
    password: masterkey

  jpa:
    database-platform: org.hibernate.community.dialect.FirebirdDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

