spring:
  datasource:
    driverClassName: org.firebirdsql.jdbc.FBDriver
    #url: jdbc:firebirdsql://localhost:3050/C:/fix/6113/6113.fdb?encoding=UTF8
    #url: jdbc:firebirdsql://localhost:3050//firebird/data/ronalds.fdb?encoding=UTF8
    url: jdbc:firebirdsql://127.0.0.1:3050//firebird/data/ronalds.fdb?encoding=UTF8
    username: SYSDBA
    password: masterkey

  jpa:
    database-platform: org.hibernate.community.dialect.FirebirdDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  # Configuracao de email (ajuste conforme seu provedor)
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}

security:
  jwt:
    # Base64 do segredo, gere um valor forte em producao
    secret: c29tZS1zdXBlci1zZWNyZXQtand0LXNpZ25pbmcta2V5LXNlZWRiYXNlNjQ=
    expiration: 3600000 # 1 hora em ms

app:
  mail:
    from: ${MAIL_FROM:}
